# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9a6e176d45b3f2359d4abd605c6f708bc2dfaf594fa67619ef0df77ff3c775f328830e77b91b28d4b92e8565b817d71df94d7f76b135e0144e70ea4f6dc7d77

test:
  secret_key_base: 07ceb5d32af322f09afee952449a28f53f82a3c6f9aba344a3dbeac687eb8939fa01c449aefd04966d745bdd0f408d340c1333b57b08fda2a9c1a65754b114cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
